language: node_js
node_js:
 - "4"
before_install: make deps-ci
before_script:
  - export DISPLAY=:99.0
  - "sh -e /etc/init.d/xvfb start"
script: make test
services:
  - redis
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.2-precise
      - ubuntu-toolchain-r-test
    packages:
      - redis-server
      - mongodb-org-server
      - mongodb-org-shell
      - g++-4.8
env:
  - CXX=g++-4.8
sudo: false
