language: node_js
node_js:
 - "6"
before_install: make deps-ci
before_script:
  - export DISPLAY=:99.0
  - "sh -e /etc/init.d/xvfb start"
services:
  - redis
  - mongodb
addons:
  apt:
    packages:
      - redis-server
sudo: false
dist: trusty
